export type ClassificationCode =
  | "G1"
  | "G3"
  | "P1"
  | "P2"
  | "P2-DUO"
  | "BLO-G1"
  | "FLEX"
  | "PP1"
  | "TEST";

export type EnrollmentPath =
  | "group"
  | "true_beginner_g1"
  | "kids"
  | "summer_kids"
  | "semi_private"
  | "semi_private_duo"
  | "private"
  | "private_intensive"
  | "private_am"
  | "private_a_la_carte"
  | "private_express"
  | "kids_private"
  | "blo_group_open"
  | "cyberteacher_phone"
  | "flex"
  | "testing"
  | "material_sale"
  | "charter";

export type PackageStatus = "active" | "inactive" | "seasonal" | "authorization_required";

export type PaymentPlanKind =
  | "full_paid"
  | "installments"
  | "monthly"
  | "by_level"
  | "custom"
  | "not_allowed";

export type ProgramPackage = {
  id: string;
  name: string;
  classificationCode: ClassificationCode;
  enrollmentPath: EnrollmentPath;
  programFamily: string;
  internalCode?: string;
  languageGroup?: "english_spanish" | "other_languages" | "pefigs" | "non_pefigs" | "any";
  levelCount?: number;
  levelRange?: string;
  durationWeeks?: number;
  licenseDurationMonths?: number;
  lessons?: number;
  paidLessons?: number;
  noChargeLessons?: number;
  totalScheduledLessons?: number;
  ratePerLesson?: number;
  tuition?: number;
  materialFee?: number;
  registrationFee?: number;
  total?: number;
  taxApplies?: boolean;
  taxRate?: number;
  totalWithTax?: number;
  groupSizeMin?: number;
  groupSizeMax?: number;
  reschedulesAllowed?: number;
  paymentPlansAllowed?: PaymentPlanKind[];
  discountsAllowed?: boolean;
  requiresAuthorization?: boolean;
  requiresCreditCardGuarantee?: boolean;
  scheduleProgramType?: string;
  scheduleNotes?: string;
  restrictions?: string[];
  sourceName: string;
  effectiveYear: number;
  status: PackageStatus;
};

export const programPackages: ProgramPackage[] = [
  {
    id: "tb_g1_levels_1_4_2026",
    name: "True Beginner + Levels 1–4",
    classificationCode: "G1",
    enrollmentPath: "true_beginner_g1",
    programFamily: "True Beginner con G1",
    levelCount: 5,
    levelRange: "True Beginner + Levels 1–4",
    durationWeeks: 35.5,
    lessons: 214,
    ratePerLesson: 8.5,
    tuition: 1819,
    materialFee: 80,
    registrationFee: 0,
    total: 1899,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "monthly", "by_level", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "group_g1",
    sourceName: "2026 Programas Grupales - True Beginner con G1",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "tb_g1_levels_1_2_2026",
    name: "True Beginner + Levels 1–2",
    classificationCode: "G1",
    enrollmentPath: "true_beginner_g1",
    programFamily: "True Beginner con G1",
    levelCount: 3,
    levelRange: "True Beginner + Levels 1–2",
    durationWeeks: 20.5,
    lessons: 124,
    ratePerLesson: 8.5,
    tuition: 1054,
    materialFee: 93,
    registrationFee: 30,
    total: 1177,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "monthly", "by_level", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "group_g1",
    sourceName: "2026 Programas Grupales - True Beginner con G1",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "g1_4_levels_2026",
    name: "G1 — 4 Levels",
    classificationCode: "G1",
    enrollmentPath: "group",
    programFamily: "Group Adults",
    levelCount: 4,
    levelRange: "Levels 1–4",
    durationWeeks: 30.5,
    lessons: 184,
    ratePerLesson: 9.5,
    tuition: 1748,
    materialFee: 103,
    registrationFee: 25,
    total: 1876,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "monthly", "by_level", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "group_g1",
    sourceName: "2026 Group Programs - G1",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "g1_2_levels_2026",
    name: "G1 — 2 Levels",
    classificationCode: "G1",
    enrollmentPath: "group",
    programFamily: "Group Adults",
    levelCount: 2,
    levelRange: "Levels 1–2 or 3–4",
    durationWeeks: 15.5,
    lessons: 94,
    ratePerLesson: 10.5,
    tuition: 987,
    materialFee: 86,
    registrationFee: 25,
    total: 1098,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "monthly", "by_level", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "group_g1",
    sourceName: "2026 Group Programs - G1",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "g1_1_level_2026",
    name: "G1 — 1 Level",
    classificationCode: "G1",
    enrollmentPath: "group",
    programFamily: "Group Adults",
    levelCount: 1,
    levelRange: "Only Level 1 or 3",
    durationWeeks: 8,
    lessons: 49,
    ratePerLesson: 13,
    tuition: 637,
    materialFee: 57,
    registrationFee: 35,
    total: 729,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "group_g1",
    sourceName: "2026 Group Programs - G1",
    effectiveYear: 2026,
    status: "active",
  },

  {
    id: "kids_g3_new_1_level_2026",
    name: "Kids & Teens G3 — New Enrollment — 1 Level",
    classificationCode: "G3",
    enrollmentPath: "kids",
    programFamily: "Kids & Teens Groups",
    levelCount: 1,
    durationWeeks: 14,
    lessons: 42,
    ratePerLesson: 10.5,
    tuition: 441,
    materialFee: 70,
    registrationFee: 20,
    total: 531,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "kids_g3",
    scheduleNotes: "Fridays 3:30–5:45 PM or Saturdays 8:00–10:15 AM / 10:15 AM–12:30 PM.",
    restrictions: [
      "Applies to Kids & Teens group programs.",
      "Book track depends on age: Look & See, Look, Time Zones, or Impact after verification.",
    ],
    sourceName: "2026 Kids & Teens Groups G3",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "kids_g3_reenroll_1_level_2026",
    name: "Kids & Teens G3 — Re-Enrollment — 1 Level",
    classificationCode: "G3",
    enrollmentPath: "kids",
    programFamily: "Kids & Teens Groups",
    levelCount: 1,
    durationWeeks: 14,
    lessons: 42,
    ratePerLesson: 9.5,
    tuition: 399,
    materialFee: 65,
    registrationFee: 0,
    total: 464,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "kids_g3",
    scheduleNotes: "Fridays 3:30–5:45 PM or Saturdays 8:00–10:15 AM / 10:15 AM–12:30 PM.",
    restrictions: ["Re-enrollment package for current or returning Kids & Teens students."],
    sourceName: "2026 Kids & Teens Groups G3",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "kids_g3_back_to_school_2026",
    name: "Kids & Teens G3 — Back to School Offer",
    classificationCode: "G3",
    enrollmentPath: "kids",
    programFamily: "Kids & Teens Groups",
    levelCount: 1,
    durationWeeks: 14,
    lessons: 42,
    ratePerLesson: 10.5,
    tuition: 441,
    materialFee: 58,
    registrationFee: 0,
    total: 499,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "kids_g3",
    scheduleNotes: "Seasonal February/August Back to School offer.",
    restrictions: ["No additional discounts apply."],
    sourceName: "2026 Kids & Teens Groups G3",
    effectiveYear: 2026,
    status: "seasonal",
  },
  {
    id: "summer_g3_kids_intensive_regular_2026",
    name: "Summer Intensive G3 Kids — Regular",
    classificationCode: "G3",
    enrollmentPath: "summer_kids",
    programFamily: "Summer Intensive Kids",
    levelCount: 1,
    durationWeeks: 4,
    lessons: 60,
    ratePerLesson: 6.75,
    tuition: 405,
    materialFee: 50,
    registrationFee: 0,
    total: 455,
    taxApplies: true,
    taxRate: 0.115,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    requiresCreditCardGuarantee: true,
    scheduleProgramType: "summer_g3",
    scheduleNotes: "Monday–Friday 9:45 AM–12:00 PM. Summer sessions June 1–26 or July 6–31, 2026.",
    restrictions: ["Payment plan requires credit card guarantee."],
    sourceName: "2026 Summer Programs Kids & Adults",
    effectiveYear: 2026,
    status: "seasonal",
  },
  {
    id: "summer_g3_kids_intensive_limited_offer_2026",
    name: "Summer Intensive G3 Kids — Limited Offer",
    classificationCode: "G3",
    enrollmentPath: "summer_kids",
    programFamily: "Summer Intensive Kids",
    levelCount: 1,
    durationWeeks: 4,
    lessons: 60,
    ratePerLesson: 6.25,
    tuition: 375,
    materialFee: 40,
    registrationFee: 0,
    total: 415,
    taxApplies: true,
    taxRate: 0.115,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    requiresCreditCardGuarantee: true,
    scheduleProgramType: "summer_g3",
    scheduleNotes: "Limited offer until April 30, 2026. Monday–Friday 9:45 AM–12:00 PM.",
    restrictions: ["Payment plan requires credit card guarantee."],
    sourceName: "2026 Summer Programs Kids & Adults",
    effectiveYear: 2026,
    status: "seasonal",
  },
  {
    id: "sp_p2_new_enrollment_level_5_2026",
    name: "Semi-private P2 — New Enrollment — Level 5",
    classificationCode: "P2",
    enrollmentPath: "semi_private",
    programFamily: "Semi-private Regular",
    levelCount: 1,
    levelRange: "Level 5",
    durationWeeks: 10,
    lessons: 40,
    ratePerLesson: 19.25,
    tuition: 770,
    materialFee: 79,
    registrationFee: 50,
    total: 899,
    groupSizeMin: 3,
    groupSizeMax: 4,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "semi_private_p2",
    scheduleNotes: "Mon/Wed or Tue/Thu 6:00–7:30 PM or 7:30–9:00 PM; Saturdays 9:00 AM–12:00 PM.",
    restrictions: ["Applies to semi-private groups with 3–4 students."],
    sourceName: "2026 Semi-Private SP/P2",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "sp_p2_reenrollment_level_5_2026",
    name: "Semi-private P2 — Re-Enrollment — Level 5",
    classificationCode: "P2",
    enrollmentPath: "semi_private",
    programFamily: "Semi-private Regular",
    levelCount: 1,
    levelRange: "Level 5",
    durationWeeks: 10,
    lessons: 40,
    ratePerLesson: 17.75,
    tuition: 710,
    materialFee: 65,
    registrationFee: 0,
    total: 775,
    groupSizeMin: 3,
    groupSizeMax: 4,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "semi_private_p2",
    scheduleNotes: "Mon/Wed or Tue/Thu 6:00–7:30 PM or 7:30–9:00 PM; Saturdays 9:00 AM–12:00 PM.",
    restrictions: ["Re-enrollment package for semi-private P2."],
    sourceName: "2026 Semi-Private SP/P2",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "sp_duo_new_1_level_2026",
    name: "Semi-private DUO — New Enrollment — 1 Level",
    classificationCode: "P2-DUO",
    enrollmentPath: "semi_private_duo",
    programFamily: "Semi-private DUO",
    levelCount: 1,
    durationWeeks: 10,
    lessons: 40,
    ratePerLesson: 29.5,
    tuition: 1180,
    materialFee: 110,
    registrationFee: 100,
    total: 1390,
    groupSizeMin: 2,
    groupSizeMax: 2,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "semi_private_duo",
    scheduleNotes: "1.5 hrs x 2 days per week or 1 day of 3 hrs. Student may choose time within operating hours.",
    restrictions: ["Only for 2 students who enroll together."],
    sourceName: "2026 Semi-Privado DUO",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "sp_duo_reenrollment_1_level_2026",
    name: "Semi-private DUO — Re-Enrollment — 1 Level",
    classificationCode: "P2-DUO",
    enrollmentPath: "semi_private_duo",
    programFamily: "Semi-private DUO",
    levelCount: 1,
    durationWeeks: 10,
    lessons: 40,
    ratePerLesson: 28,
    tuition: 1120,
    materialFee: 79,
    registrationFee: 0,
    total: 1199,
    groupSizeMin: 2,
    groupSizeMax: 2,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "semi_private_duo",
    scheduleNotes: "1.5 hrs x 2 days per week or 1 day of 3 hrs. Student may choose time within operating hours.",
    restrictions: ["Only for 2 students who enroll together."],
    sourceName: "2026 Semi-Privado DUO",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "sp_duo_new_2_levels_2026",
    name: "Semi-private DUO — New Enrollment — 2 Levels",
    classificationCode: "P2-DUO",
    enrollmentPath: "semi_private_duo",
    programFamily: "Semi-private DUO",
    levelCount: 2,
    durationWeeks: 20,
    lessons: 80,
    ratePerLesson: 28,
    tuition: 2240,
    materialFee: 120,
    registrationFee: 100,
    total: 2460,
    groupSizeMin: 2,
    groupSizeMax: 2,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "semi_private_duo",
    scheduleNotes: "1.5 hrs x 2 days per week or 1 day of 3 hrs. Student may choose time within operating hours.",
    restrictions: ["Only for 2 students who enroll together."],
    sourceName: "2026 Semi-Privado DUO",
    effectiveYear: 2026,
    status: "active",
  },

  {
    id: "private_premium_cp_eng_spa_new_1_level_2026",
    name: "Private Premium CP — English/Spanish — New Enrollment — 1 Level",
    classificationCode: "P1",
    enrollmentPath: "private",
    programFamily: "Private Premium CP",
    internalCode: "CP",
    languageGroup: "english_spanish",
    levelCount: 1,
    durationWeeks: 10,
    lessons: 40,
    ratePerLesson: 53.25,
    tuition: 2130,
    materialFee: 80,
    registrationFee: 65,
    total: 2275,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "private_regular",
    scheduleNotes: "1.5 hrs x 2 days/week or 1 day of 3 hrs. Student may choose class time within operating hours.",
    sourceName: "2026 Private P1 Regular Premium - English & Spanish",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_premium_cp_eng_spa_new_2_levels_2026",
    name: "Private Premium CP — English/Spanish — New Enrollment — 2 Levels",
    classificationCode: "P1",
    enrollmentPath: "private",
    programFamily: "Private Premium CP",
    internalCode: "CP",
    languageGroup: "english_spanish",
    levelCount: 2,
    durationWeeks: 20,
    lessons: 80,
    ratePerLesson: 51.25,
    tuition: 4100,
    materialFee: 120,
    registrationFee: 65,
    total: 4285,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "private_regular",
    scheduleNotes: "1.5 hrs x 2 days/week or 1 day of 3 hrs. Student may choose class time within operating hours.",
    sourceName: "2026 Private P1 Regular Premium - English & Spanish",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_premium_cp_eng_spa_reenroll_1_level_2026",
    name: "Private Premium CP — English/Spanish — Re-Enrollment — 1 Level",
    classificationCode: "P1",
    enrollmentPath: "private",
    programFamily: "Private Premium CP",
    internalCode: "CP",
    languageGroup: "english_spanish",
    levelCount: 1,
    durationWeeks: 10,
    lessons: 40,
    ratePerLesson: 52,
    tuition: 2080,
    materialFee: 80,
    registrationFee: 0,
    total: 2160,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "private_regular",
    sourceName: "2026 Private P1 Regular Premium - English & Spanish",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_premium_cp_eng_spa_reenroll_2_levels_2026",
    name: "Private Premium CP — English/Spanish — Re-Enrollment — 2 Levels",
    classificationCode: "P1",
    enrollmentPath: "private",
    programFamily: "Private Premium CP",
    internalCode: "CP",
    languageGroup: "english_spanish",
    levelCount: 2,
    durationWeeks: 20,
    lessons: 80,
    ratePerLesson: 49.25,
    tuition: 3940,
    materialFee: 59,
    registrationFee: 0,
    total: 3999,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "private_regular",
    sourceName: "2026 Private P1 Regular Premium - English & Spanish",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_premium_cp_other_languages_new_1_level_2026",
    name: "Private Premium CP — Other Languages — New Enrollment — 1 Level",
    classificationCode: "P1",
    enrollmentPath: "private",
    programFamily: "Private Premium CP",
    internalCode: "CP",
    languageGroup: "other_languages",
    levelCount: 1,
    durationWeeks: 10,
    lessons: 40,
    ratePerLesson: 54,
    tuition: 2160,
    materialFee: 110,
    registrationFee: 100,
    total: 2370,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "private_regular",
    sourceName: "2026 Private P1 Regular Premium - Other Languages",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_premium_cp_other_languages_new_2_levels_2026",
    name: "Private Premium CP — Other Languages — New Enrollment — 2 Levels",
    classificationCode: "P1",
    enrollmentPath: "private",
    programFamily: "Private Premium CP",
    internalCode: "CP",
    languageGroup: "other_languages",
    levelCount: 2,
    durationWeeks: 20,
    lessons: 80,
    ratePerLesson: 53,
    tuition: 4240,
    materialFee: 150,
    registrationFee: 100,
    total: 4490,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "private_regular",
    sourceName: "2026 Private P1 Regular Premium - Other Languages",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_premium_cp_other_languages_reenroll_1_level_2026",
    name: "Private Premium CP — Other Languages — Re-Enrollment — 1 Level",
    classificationCode: "P1",
    enrollmentPath: "private",
    programFamily: "Private Premium CP",
    internalCode: "CP",
    languageGroup: "other_languages",
    levelCount: 1,
    durationWeeks: 10,
    lessons: 40,
    ratePerLesson: 53,
    tuition: 2120,
    materialFee: 89,
    registrationFee: 0,
    total: 2209,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "private_regular",
    sourceName: "2026 Private P1 Regular Premium - Other Languages",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_premium_cp_other_languages_reenroll_2_levels_2026",
    name: "Private Premium CP — Other Languages — Re-Enrollment — 2 Levels",
    classificationCode: "P1",
    enrollmentPath: "private",
    programFamily: "Private Premium CP",
    internalCode: "CP",
    languageGroup: "other_languages",
    levelCount: 2,
    durationWeeks: 20,
    lessons: 80,
    ratePerLesson: 52.25,
    tuition: 4180,
    materialFee: 150,
    registrationFee: 0,
    total: 4330,
    reschedulesAllowed: 10,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "private_regular",
    sourceName: "2026 Private P1 Regular Premium - Other Languages",
    effectiveYear: 2026,
    status: "active",
  },

  {
    id: "private_fixed_cp_eng_spa_1_level_2026",
    name: "Private Fixed Term CP — English/Spanish — 1 Level",
    classificationCode: "P1",
    enrollmentPath: "private_intensive",
    programFamily: "Private Fixed Term",
    internalCode: "CP",
    languageGroup: "english_spanish",
    levelCount: 1,
    durationWeeks: 5,
    paidLessons: 32,
    noChargeLessons: 8,
    totalScheduledLessons: 40,
    ratePerLesson: 51.25,
    tuition: 1640,
    materialFee: 74,
    registrationFee: 35,
    total: 1749,
    reschedulesAllowed: 2,
    paymentPlansAllowed: ["full_paid", "custom"],
    discountsAllowed: false,
    scheduleProgramType: "private_intensive",
    scheduleNotes: "1.5 hrs x 4 days/week or 2 days of 3 hrs.",
    sourceName: "2026 Private Fixed Term & Price Standard",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_fixed_cp_eng_spa_2_levels_2026",
    name: "Private Fixed Term CP — English/Spanish — 2 Levels",
    classificationCode: "P1",
    enrollmentPath: "private_intensive",
    programFamily: "Private Fixed Term",
    internalCode: "CP",
    languageGroup: "english_spanish",
    levelCount: 2,
    durationWeeks: 10,
    paidLessons: 64,
    noChargeLessons: 16,
    totalScheduledLessons: 80,
    ratePerLesson: 49,
    tuition: 3136,
    materialFee: 120,
    registrationFee: 35,
    total: 3291,
    reschedulesAllowed: 2,
    paymentPlansAllowed: ["full_paid", "custom"],
    discountsAllowed: false,
    scheduleProgramType: "private_intensive",
    scheduleNotes: "1.5 hrs x 4 days/week or 2 days of 3 hrs.",
    sourceName: "2026 Private Fixed Term & Price Standard",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_fixed_cp_other_languages_1_level_2026",
    name: "Private Fixed Term CP — Other Languages — 1 Level",
    classificationCode: "P1",
    enrollmentPath: "private_intensive",
    programFamily: "Private Fixed Term",
    internalCode: "CP",
    languageGroup: "other_languages",
    levelCount: 1,
    durationWeeks: 5,
    lessons: 40,
    ratePerLesson: 46,
    tuition: 1840,
    materialFee: 74,
    registrationFee: 35,
    total: 1949,
    reschedulesAllowed: 2,
    paymentPlansAllowed: ["full_paid", "custom"],
    discountsAllowed: false,
    scheduleProgramType: "private_intensive",
    scheduleNotes: "1.5 hrs x 4 days/week or 2 days of 3 hrs.",
    sourceName: "2026 Private Fixed Term & Price Standard",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_fixed_cp_other_languages_2_levels_2026",
    name: "Private Fixed Term CP — Other Languages — 2 Levels",
    classificationCode: "P1",
    enrollmentPath: "private_intensive",
    programFamily: "Private Fixed Term",
    internalCode: "CP",
    languageGroup: "other_languages",
    levelCount: 2,
    durationWeeks: 10,
    lessons: 80,
    ratePerLesson: 45,
    tuition: 3600,
    materialFee: 120,
    registrationFee: 35,
    total: 3755,
    reschedulesAllowed: 2,
    paymentPlansAllowed: ["full_paid", "custom"],
    discountsAllowed: false,
    scheduleProgramType: "private_intensive",
    scheduleNotes: "1.5 hrs x 4 days/week or 2 days of 3 hrs.",
    sourceName: "2026 Private Fixed Term & Price Standard",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_fixed_term_summer_cp_eng_spa_1_level_2026",
    name: "Private Fixed Term Summer CP — English/Spanish — 1 Level",
    classificationCode: "P1",
    enrollmentPath: "private_intensive",
    programFamily: "Private Fixed Term Summer 2026",
    internalCode: "CP",
    languageGroup: "english_spanish",
    levelCount: 1,
    durationWeeks: 5,
    paidLessons: 32,
    noChargeLessons: 8,
    totalScheduledLessons: 40,
    ratePerLesson: 47.5,
    tuition: 1520,
    materialFee: 29,
    registrationFee: 0,
    total: 1549,
    reschedulesAllowed: 2,
    paymentPlansAllowed: ["full_paid", "custom"],
    discountsAllowed: true,
    scheduleProgramType: "private_intensive",
    scheduleNotes: "Summer offer. June 1–July 2, 2026. 1.5 hrs x 4 days/week or 2 days of 3 hrs.",
    restrictions: ["Applies only to English or Spanish for adults."],
    sourceName: "2026 Private Fixed Term Summer Only",
    effectiveYear: 2026,
    status: "seasonal",
  },
  {
    id: "private_fixed_term_summer_cp_eng_spa_2_levels_2026",
    name: "Private Fixed Term Summer CP — English/Spanish — 2 Levels",
    classificationCode: "P1",
    enrollmentPath: "private_intensive",
    programFamily: "Private Fixed Term Summer 2026",
    internalCode: "CP",
    languageGroup: "english_spanish",
    levelCount: 2,
    durationWeeks: 10,
    paidLessons: 64,
    noChargeLessons: 16,
    totalScheduledLessons: 80,
    ratePerLesson: 47.5,
    tuition: 3040,
    materialFee: 58,
    registrationFee: 0,
    total: 3098,
    reschedulesAllowed: 2,
    paymentPlansAllowed: ["full_paid", "custom"],
    discountsAllowed: true,
    scheduleProgramType: "private_intensive",
    scheduleNotes: "Summer offer. June 1–July 2, 2026. 1.5 hrs x 4 days/week or 2 days of 3 hrs.",
    restrictions: ["Applies only to English or Spanish for adults."],
    sourceName: "2026 Private Fixed Term Summer Only",
    effectiveYear: 2026,
    status: "seasonal",
  },
  {
    id: "private_premium_cp_am_only_1_level_2026",
    name: "Private Premium CP — AM Only — 1 Level",
    classificationCode: "P1",
    enrollmentPath: "private_am",
    programFamily: "Private Premium AM Only",
    internalCode: "CP",
    languageGroup: "english_spanish",
    levelCount: 1,
    durationWeeks: 9,
    lessons: 36,
    ratePerLesson: 40,
    tuition: 1440,
    materialFee: 59,
    registrationFee: 0,
    total: 1499,
    reschedulesAllowed: 5,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "private_am",
    scheduleNotes: "F2F only. Allowed times: 9:00–10:30 AM, 10:30 AM–12:00 PM, 1:00–2:30 PM, 2:30–4:00 PM.",
    restrictions: ["No other offers apply.", "Only consumer private; not corporate.", "Face-to-face only."],
    sourceName: "2026 Private Regular P1 AM Only",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_a_la_carte_3_lessons_2026",
    name: "Private A La Carte — 3 Lessons",
    classificationCode: "P1",
    enrollmentPath: "private_a_la_carte",
    programFamily: "Private A La Carte",
    lessons: 3,
    ratePerLesson: 60,
    tuition: 180,
    materialFee: 50,
    registrationFee: 50,
    total: 280,
    taxApplies: true,
    paymentPlansAllowed: ["not_allowed"],
    discountsAllowed: false,
    scheduleProgramType: "private_a_la_carte",
    restrictions: ["Paid upfront only.", "No payment plan.", "No discounts."],
    sourceName: "2026 Private A La Carte P1",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_a_la_carte_5_lessons_2026",
    name: "Private A La Carte — 5 Lessons",
    classificationCode: "P1",
    enrollmentPath: "private_a_la_carte",
    programFamily: "Private A La Carte",
    lessons: 5,
    ratePerLesson: 60,
    tuition: 300,
    materialFee: 50,
    registrationFee: 50,
    total: 400,
    taxApplies: true,
    paymentPlansAllowed: ["not_allowed"],
    discountsAllowed: false,
    scheduleProgramType: "private_a_la_carte",
    restrictions: ["Paid upfront only.", "No payment plan.", "No discounts."],
    sourceName: "2026 Private A La Carte P1",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_a_la_carte_10_lessons_2026",
    name: "Private A La Carte — 10 Lessons",
    classificationCode: "P1",
    enrollmentPath: "private_a_la_carte",
    programFamily: "Private A La Carte",
    lessons: 10,
    ratePerLesson: 60,
    tuition: 600,
    materialFee: 50,
    registrationFee: 50,
    total: 700,
    taxApplies: true,
    paymentPlansAllowed: ["not_allowed"],
    discountsAllowed: false,
    scheduleProgramType: "private_a_la_carte",
    restrictions: ["Paid upfront only.", "No payment plan.", "No discounts."],
    sourceName: "2026 Private A La Carte P1",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "private_express_levels_5_8_2026",
    name: "Private Express — Levels 5–8",
    classificationCode: "P1",
    enrollmentPath: "private_express",
    programFamily: "Private Express",
    levelRange: "Levels 5–8",
    durationWeeks: 5,
    lessons: 20,
    ratePerLesson: 51,
    tuition: 1020,
    materialFee: 50,
    registrationFee: 25,
    total: 1095,
    requiresCreditCardGuarantee: true,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "private_express",
    scheduleNotes: "2 days/week, 1.5 hrs/day.",
    restrictions: ["Only available for levels 5, 6, 7, and 8."],
    sourceName: "2026 Private Express Only Levels 5-8",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "kids_private_1_level_2026",
    name: "Kids Private — 1 Level",
    classificationCode: "P1",
    enrollmentPath: "kids_private",
    programFamily: "Kids Private",
    levelCount: 1,
    durationWeeks: 9,
    lessons: 36,
    ratePerLesson: 50,
    tuition: 1800,
    materialFee: 85,
    registrationFee: 50,
    total: 1935,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "kids_private",
    sourceName: "2026 Berlitz Kids Private",
    effectiveYear: 2026,
    status: "active",
  },

  {
    id: "blo_open_group_english_spanish_2026",
    name: "BLO Open Group — English/Spanish",
    classificationCode: "BLO-G1",
    enrollmentPath: "blo_group_open",
    programFamily: "BLO Open Groups",
    languageGroup: "english_spanish",
    levelCount: 1,
    lessons: 64,
    ratePerLesson: 9.75,
    tuition: 624,
    materialFee: 51,
    registrationFee: 20,
    total: 695,
    groupSizeMin: 3,
    groupSizeMax: 6,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "blo_open_group",
    scheduleNotes: "BLO schedule must be verified before offering. 48 hours of 60 minutes equals 64 lessons of 45 minutes.",
    restrictions: ["Only for Open Groups, not Charter.", "Must verify availability before offering."],
    sourceName: "2026 BLO Groups Open",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "blo_open_group_standard_languages_2026",
    name: "BLO Open Group — Standard Languages",
    classificationCode: "BLO-G1",
    enrollmentPath: "blo_group_open",
    programFamily: "BLO Open Groups",
    languageGroup: "other_languages",
    levelCount: 1,
    lessons: 64,
    ratePerLesson: 14,
    tuition: 896,
    materialFee: 85,
    registrationFee: 25,
    total: 1006,
    groupSizeMin: 3,
    groupSizeMax: 6,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "blo_open_group",
    scheduleNotes: "German, French, Portuguese, Mandarin, Dutch, Swedish, Japanese, Italian. Must verify availability before offering.",
    restrictions: ["Only for Open Groups, not Charter.", "Must verify availability before offering."],
    sourceName: "2026 BLO Groups Open",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "blo_open_group_other_languages_2026",
    name: "BLO Open Group — Other Languages",
    classificationCode: "BLO-G1",
    enrollmentPath: "blo_group_open",
    programFamily: "BLO Open Groups",
    languageGroup: "other_languages",
    levelCount: 1,
    lessons: 64,
    ratePerLesson: 15,
    tuition: 960,
    materialFee: 79,
    registrationFee: 30,
    total: 1069,
    groupSizeMin: 3,
    groupSizeMax: 6,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    scheduleProgramType: "blo_open_group",
    scheduleNotes: "Any other language. Must verify availability before offering.",
    restrictions: ["Only for Open Groups, not Charter.", "Must verify availability before offering."],
    sourceName: "2026 BLO Groups Open",
    effectiveYear: 2026,
    status: "active",
  },
  {
    id: "winter_intensive_g1_adults_paid_full_2026",
    name: "Winter Intensive G1 Adults — Paid in Full",
    classificationCode: "G1",
    enrollmentPath: "group",
    programFamily: "Winter Intensive G1 Adults",
    levelCount: 1,
    durationWeeks: 4,
    lessons: 36,
    ratePerLesson: 11,
    tuition: 396,
    materialFee: 50,
    registrationFee: 0,
    total: 446,
    taxApplies: true,
    taxRate: 0.115,
    groupSizeMin: 5,
    groupSizeMax: 8,
    paymentPlansAllowed: ["full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "winter_g1",
    scheduleNotes: "Monday, Tuesday & Thursday 6:45–9:00 PM. November 30–December 23, 2026.",
    sourceName: "2026 Winter G1 Offer",
    effectiveYear: 2026,
    status: "seasonal",
  },
  {
    id: "winter_intensive_g1_adults_payment_plan_2026",
    name: "Winter Intensive G1 Adults — Payment Plan",
    classificationCode: "G1",
    enrollmentPath: "group",
    programFamily: "Winter Intensive G1 Adults",
    levelCount: 1,
    durationWeeks: 4,
    lessons: 36,
    ratePerLesson: 12,
    tuition: 432,
    materialFee: 46,
    registrationFee: 20,
    total: 498,
    taxApplies: true,
    taxRate: 0.115,
    groupSizeMin: 5,
    groupSizeMax: 8,
    requiresCreditCardGuarantee: true,
    paymentPlansAllowed: ["installments"],
    discountsAllowed: false,
    scheduleProgramType: "winter_g1",
    scheduleNotes: "Monday, Tuesday & Thursday 6:45–9:00 PM. November 30–December 23, 2026.",
    restrictions: ["Payment plan requires credit card guarantee."],
    sourceName: "2026 Winter G1 Offer",
    effectiveYear: 2026,
    status: "seasonal",
  },

  {
    id: "cyt_live_3_months_12_pl_2025_09",
    name: "CyberTeacher Live 3 months + 12 Phone Lessons",
    classificationCode: "PP1",
    enrollmentPath: "cyberteacher_phone",
    programFamily: "CyberTeacher Live + Phone Lessons",
    licenseDurationMonths: 3,
    lessons: 12,
    tuition: 395,
    taxApplies: true,
    taxRate: 0.115,
    totalWithTax: 440.43,
    paymentPlansAllowed: ["full_paid"],
    discountsAllowed: false,
    scheduleProgramType: "cyberteacher_phone",
    restrictions: ["No payment plan.", "No discounts."],
    sourceName: "CyberTeacher Live + Phone Lessons as of September 23, 2025",
    effectiveYear: 2025,
    status: "active",
  },
  {
    id: "cyt_live_6_months_24_pl_2025_09",
    name: "CyberTeacher Live 6 months + 24 Phone Lessons",
    classificationCode: "PP1",
    enrollmentPath: "cyberteacher_phone",
    programFamily: "CyberTeacher Live + Phone Lessons",
    licenseDurationMonths: 6,
    lessons: 24,
    tuition: 625,
    taxApplies: true,
    taxRate: 0.115,
    totalWithTax: 696.88,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    requiresCreditCardGuarantee: true,
    scheduleProgramType: "cyberteacher_phone",
    restrictions: [
      "Phone Lessons must be activated according to payment received.",
      "Register the difference in LCMS after the following payment.",
      "Silver Bullets limited to 3 per month when authorized.",
    ],
    sourceName: "CyberTeacher Live + Phone Lessons as of September 23, 2025",
    effectiveYear: 2025,
    status: "active",
  },
  {
    id: "cyt_live_12_months_24_pl_2025_09",
    name: "CyberTeacher Live 12 months + 24 Phone Lessons",
    classificationCode: "PP1",
    enrollmentPath: "cyberteacher_phone",
    programFamily: "CyberTeacher Live + Phone Lessons",
    licenseDurationMonths: 12,
    lessons: 24,
    tuition: 825,
    taxApplies: true,
    taxRate: 0.115,
    totalWithTax: 919.88,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    requiresCreditCardGuarantee: true,
    scheduleProgramType: "cyberteacher_phone",
    restrictions: [
      "Phone Lessons must be activated according to payment received.",
      "Register the difference in LCMS after the following payment.",
      "Silver Bullets limited to 3 per month when authorized.",
    ],
    sourceName: "CyberTeacher Live + Phone Lessons as of September 23, 2025",
    effectiveYear: 2025,
    status: "active",
  },
  {
    id: "cyt_live_12_months_48_pl_2025_09",
    name: "CyberTeacher Live 12 months + 48 Phone Lessons",
    classificationCode: "PP1",
    enrollmentPath: "cyberteacher_phone",
    programFamily: "CyberTeacher Live + Phone Lessons",
    licenseDurationMonths: 12,
    lessons: 48,
    tuition: 1095,
    taxApplies: true,
    taxRate: 0.115,
    totalWithTax: 1220.93,
    paymentPlansAllowed: ["installments", "full_paid"],
    discountsAllowed: true,
    requiresCreditCardGuarantee: true,
    scheduleProgramType: "cyberteacher_phone",
    restrictions: [
      "Phone Lessons price changes for this package.",
      "Phone Lessons must be activated according to payment received.",
      "Register the difference in LCMS after the following payment.",
      "Silver Bullets limited to 3 per month when authorized.",
    ],
    sourceName: "CyberTeacher Live + Phone Lessons as of September 23, 2025",
    effectiveYear: 2025,
    status: "active",
  },
  {
    id: "flex_license_6_months_2025",
    name: "FLEX — Licencia 6 meses",
    classificationCode: "FLEX",
    enrollmentPath: "flex",
    programFamily: "FLEX License",
    licenseDurationMonths: 6,
    tuition: 599,
    taxApplies: true,
    taxRate: 0.115,
    totalWithTax: 667.89,
    paymentPlansAllowed: ["installments"],
    discountsAllowed: false,
    scheduleProgramType: "flex_license",
    sourceName: "FLEX License 2025",
    effectiveYear: 2025,
    status: "active",
  },
  {
    id: "flex_license_12_months_2025",
    name: "FLEX — Licencia 12 meses",
    classificationCode: "FLEX",
    enrollmentPath: "flex",
    programFamily: "FLEX License",
    licenseDurationMonths: 12,
    tuition: 1099,
    taxApplies: true,
    taxRate: 0.115,
    totalWithTax: 1225.39,
    paymentPlansAllowed: ["installments"],
    discountsAllowed: false,
    scheduleProgramType: "flex_license",
    sourceName: "FLEX License 2025",
    effectiveYear: 2025,
    status: "active",
  },
];

export function getProgramPackagesByPath(enrollmentPath: EnrollmentPath) {
  return programPackages.filter(
    (programPackage) =>
      programPackage.enrollmentPath === enrollmentPath &&
      programPackage.status !== "inactive"
  );
}

export function getProgramPackageById(packageId: string) {
  return programPackages.find((programPackage) => programPackage.id === packageId);
}

export function getClassificationLabel(code: ClassificationCode) {
  const labels: Record<ClassificationCode, string> = {
    G1: "Group Adult",
    G3: "Kids & Teens Group",
    P1: "Private",
    P2: "Semi-private",
    "P2-DUO": "Semi-private DUO",
    "BLO-G1": "BLO Open Group",
    FLEX: "Flex License",
    PP1: "CyberTeacher with Phone Lessons",
    TEST: "Testing Services",
  };

  return labels[code];
}
